spring.application.name=collectionOfRecipes

#?????? ??????????? ? PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/recipe_app
spring.datasource.username=postgres
spring.datasource.password=BTS08052005
spring.datasource.driver-class-name=org.postgresql.Driver

# ????????? Hibernate/JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ?????????, ??? ?? ? ??? ???? ?????:
spring.security.user.name=admin
spring.security.user.password=secret
