spring.application.name=collectionOfRecipes

server.address=0.0.0.0
server.http2.enabled=false

#?????? ??????????? ? PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/recipe_app
spring.datasource.username=postgres
spring.datasource.password=${RECIPES_DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ????????? Hibernate/JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# ?????????, ??? ?? ? ??? ???? ?????:
spring.security.user.name=admin
spring.security.user.password=${RECIPES_USER_PASSWORD}

app.jwt.secret=${RECIPES_JWT_SECRET}
app.jwt.lifetime=PT30M

spring.application.encoding.charset=UTF-8
spring.application.encoding.force=true

logging.charset.console=UTF-8
logging.charset.file=UTF-8

spring.web.locale=ru_RU
spring.mvc.locale=ru_RU

management.endpoint.health.enabled=true
management.endpoints.web.exposure.include=health

# Gmail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=resipesender@gmail.com
spring.mail.password=${RECIPES_MAIL_PASSWORD}
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000


#???????????
logging.file.name=logs/application.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %-40.40logger{36} - %msg%n

# ?????? ???????????
logging.level.com.group.collectionofrecipes=DEBUG
logging.level.org.springframework=INFO
logging.level.org.springframework.security=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=INFO
