spring.application.name=collectionOfRecipes

#?????? ??????????? ? PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/recipe_app
spring.datasource.username=postgres
spring.datasource.password=${MY_APP_DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ????????? Hibernate/JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ?????????, ??? ?? ? ??? ???? ?????:
spring.security.user.name=admin
spring.security.user.password=${MY_APP_USER_PASSWORD}

app.jwt.secret=${MY_APP_JWT_SECRET}
app.jwt.lifetime=PT30M

spring.application.encoding.charset=UTF-8
spring.application.encoding.force=true

logging.charset.console=UTF-8
logging.charset.file=UTF-8

spring.web.locale=ru_RU
spring.mvc.locale=ru_RU

management.endpoint.health.enabled=true
management.endpoints.web.exposure.include=health
