-- MySQL Script generated by MySQL Workbench
-- Sat Sep 27 22:33:32 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema recipebook
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema recipebook
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `recipebook` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `category_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`category_id`));

USE `recipebook` ;

-- -----------------------------------------------------
-- Table `recipebook`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recipebook`.`categories` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`category_id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE,
  INDEX `idx_category_name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `recipebook`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recipebook`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `photo` VARCHAR(45) NULL,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  INDEX `idx_username` (`username` ASC) VISIBLE,
  INDEX `idx_email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `recipebook`.`recipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recipebook`.`recipes` (
  `recipe_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `instructions` TEXT NOT NULL,
  `cooking_time` INT NOT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `author_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `count_of_servings` INT NOT NULL,
  `total_rating` INT NULL,
  `count_of_ratings` INT NULL,
  PRIMARY KEY (`recipe_id`),
  INDEX `idx_recipe_title` (`title` ASC) VISIBLE,
  INDEX `idx_author` (`author_id` ASC) VISIBLE,
  INDEX `idx_category` (`category_id` ASC) VISIBLE,
  INDEX `idx_created_at` (`created_at` ASC) VISIBLE,
  CONSTRAINT `recipes_ibfk_1`
    FOREIGN KEY (`author_id`)
    REFERENCES `recipebook`.`users` (`user_id`)
    ON DELETE CASCADE,
  CONSTRAINT `recipes_ibfk_2`
    FOREIGN KEY (`category_id`)
    REFERENCES `recipebook`.`categories` (`category_id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `recipebook`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recipebook`.`comments` (
  `comment_id` INT NOT NULL AUTO_INCREMENT,
  `recipe_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `comment_text` TEXT NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`comment_id`),
  INDEX `idx_recipe_comments` (`recipe_id` ASC) VISIBLE,
  INDEX `idx_user_comments` (`user_id` ASC) VISIBLE,
  CONSTRAINT `comments_ibfk_1`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `recipebook`.`recipes` (`recipe_id`)
    ON DELETE CASCADE,
  CONSTRAINT `comments_ibfk_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `recipebook`.`users` (`user_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `recipebook`.`favorites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recipebook`.`favorites` (
  `favorite_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `recipe_id` INT NOT NULL,
  PRIMARY KEY (`favorite_id`),
  UNIQUE INDEX `unique_favorite` (`user_id` ASC, `recipe_id` ASC) VISIBLE,
  INDEX `idx_user_favorites` (`user_id` ASC) VISIBLE,
  INDEX `idx_recipe_favorites` (`recipe_id` ASC) VISIBLE,
  CONSTRAINT `favorites_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `recipebook`.`users` (`user_id`)
    ON DELETE CASCADE,
  CONSTRAINT `favorites_ibfk_2`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `recipebook`.`recipes` (`recipe_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `recipebook`.`ingredients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recipebook`.`ingredients` (
  `ingredient_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `unit` VARCHAR(20) NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ingredient_id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE,
  INDEX `idx_ingredient_name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `recipebook`.`ratings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recipebook`.`ratings` (
  `rating_id` INT NOT NULL AUTO_INCREMENT,
  `recipe_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `rating` TINYINT NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`rating_id`),
  UNIQUE INDEX `unique_rating` (`recipe_id` ASC, `user_id` ASC) VISIBLE,
  INDEX `idx_recipe_ratings` (`recipe_id` ASC) VISIBLE,
  INDEX `idx_user_ratings` (`user_id` ASC) VISIBLE,
  CONSTRAINT `ratings_ibfk_1`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `recipebook`.`recipes` (`recipe_id`)
    ON DELETE CASCADE,
  CONSTRAINT `ratings_ibfk_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `recipebook`.`users` (`user_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `recipebook`.`recipe_ingredients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recipebook`.`recipe_ingredients` (
  `recipe_ingredient_id` INT NOT NULL AUTO_INCREMENT,
  `recipe_id` INT NOT NULL,
  `ingredient_id` INT NOT NULL,
  `quantity` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`recipe_ingredient_id`),
  UNIQUE INDEX `unique_recipe_ingredient` (`recipe_id` ASC, `ingredient_id` ASC) VISIBLE,
  INDEX `idx_recipe` (`recipe_id` ASC) VISIBLE,
  INDEX `idx_ingredient` (`ingredient_id` ASC) VISIBLE,
  CONSTRAINT `recipe_ingredients_ibfk_1`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `recipebook`.`recipes` (`recipe_id`)
    ON DELETE CASCADE,
  CONSTRAINT `recipe_ingredients_ibfk_2`
    FOREIGN KEY (`ingredient_id`)
    REFERENCES `recipebook`.`ingredients` (`ingredient_id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
